[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "src"
description = "Code to translate Publico news into several languages."
readme = "README.md"
version = "0.0.1"
dependencies = [
    "deep_translator==1.11.4",
    "pymongo==4.6.2"
]
requires-python = "~=3.11"

[project.optional-dependencies]
test = ["pytest==7.4.3"]
lint = ["ruff"]
